version: '3.3'
services:
  redis:
    image: redis
    ports:
      - '6973:6973'
  redisinsight:
    volumes:
      - '/c/temp/redis-test:/db'
    ports:
      - '8001:8001'
    image: redislabs/redisinsight